### ISSUE TITLE
java.lang.NoSuchMethodError: org.asciidoctor.Asciidoctor.requireLibraries(Ljava/util/Collection;)V

### ISSUE THREAD

**Issue by rmpestano** [cukespace/arquillian-asciidoctor-extension#1]
Hi,

Its probably a windows issue but I'm getting the error below when calling     

> asciidoctor.requireLibraries(requires);

```
java.lang.NoSuchMethodError: org.asciidoctor.Asciidoctor.requireLibraries(Ljava/util/Collection;)V
	at com.github.cukespace.arquillian.asciidoctor.AsciidoctorObserver.render(AsciidoctorObserver.java:166)
	at com.github.cukespace.arquillian.asciidoctor.AsciidoctorObserver.renderAll(AsciidoctorObserver.java:70)
	at com.github.cukespace.arquillian.asciidoctor.AsciidoctorObserver.init(AsciidoctorObserver.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.core.impl.ManagerImpl.shutdown(ManagerImpl.java:303)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.shutdown(EventTestRunnerAdaptor.java:164)
	at org.jboss.arquillian.junit.Arquillian$1.shutdown(Arquillian.java:146)
	at org.jboss.arquillian.junit.Arquillian$1.testRunFinished(Arquillian.java:132)
	at org.junit.runner.notification.RunNotifier$2.notifyListener(RunNotifier.java:95)
```

the requires is an empty array, also gemPath used to create Asciidoctor instance is blank ("").

**Comment by r-tt** [comment]
that's the defaults of the mvn plugin, we can use the ones which fit the need. Want to do a PR? Didnt get time to add all the tests i wanted to ensure all config entries work but backbone to do that is there

**Comment by rmpestano** [comment]
sure can send a PR, I've just calling requireLibraries if its not empty and worked nicely. 

The question is what is, do we need it at first place? 

If I undestand the requireLibraries() is a way to usersprovide different libs (eg jruby-complete 9.x instead of 1.7,x) to asciidoctor?

I'll add more tests

**Comment by r-tt** [comment]
it is used to add adoc extensions like diagram one

**Comment by rmpestano** [comment]
Alright, I did a manual "functional test", configured this extension in cukespace examples project and generated html docs. 

I updated cukedoctor(1.0.3) and asciidoctorJ(1.5.3) to latest version.

Had a problem with headerFooter which must be true otherwise Cukedoctor will fail because it uses footer div to add its custom js scripts and custom footer. I think I can handle that soon.

For pdf backend I had the exception below (mybe its related to windows, didn't look after):

```
java.lang.RuntimeException: Could not run @AfterSuite
	at org.jboss.arquillian.junit.Arquillian$1.shutdown(Arquillian.java:158)
	at org.jboss.arquillian.junit.Arquillian$1.testRunFinished(Arquillian.java:132)
	at org.junit.runner.notification.RunNotifier$2.notifyListener(RunNotifier.java:95)
	at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:61)
	at org.junit.runner.notification.RunNotifier.fireTestRunFinished(RunNotifier.java:92)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:87)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `activate' for nil:NilClass
	at RUBY.try_activate(/C:/Users/rafael-pestano/.m2/repository/org/jruby/jruby-complete/1.7.21/jruby-complete-1.7.21.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems.rb:198)
	at RUBY.require(/C:/Users/rafael-pestano/.m2/repository/org/jruby/jruby-complete/1.7.21/jruby-complete-1.7.21.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:126)
	at RUBY.(root)(<script>:1)
```

**Comment by rmannibucau** [comment]
for headerFooter i kept the same behavior as the mvn plugin but it is compatible with cukespace configuring it (should just be doc-ed i think). idea is to keep it easier to give back to adoc community.

i downgraded jruby to avoid the windows issue but maybe we should upgrade to 9 rather than downgrading.

**Comment by rmpestano** [comment]
Yeap, for header and footer not an issue here, that's a cukedoctor problem.

For pdf on windows is a no go for now, I also think we should upgrade.

Overall the extension is working great (will test pdf at home) and I think it fixes https://github.com/cukespace/cukespace/pull/56.

About tests, I see that we have dependent test, one to generate documentation with arquillian and another to assert the docs content.

Can't we do it only with arquillian, like for example in an event that runs after document is generated, something like this: https://github.com/arquillian/arquillian-examples/blob/master/arquillian-lifecycle-extension-tutorial/src/test/java/org/arquillian/tutorial/extension/lifecycle/LifecycleTestCase.java#L62

**Comment by rmannibucau** [comment]
The only way to do it in the arquillian test is to do it after arquillian is executed. A workaround would be to add the test as arquillian observer but it would break the arquillian concept so using an execution to trigger some data generation and the extension execution and another execution to validate the previous execution was as expected. I'm not seeing another way to keep it "clean" and not with a super complicated lifecycle in the test itself. Happy to enhance it if you think we can but I'd like to not touch at all the "main" lifecycle since the rendering only makes sense after all tests.

Side note: an enhancement can be to create asciidoctor instance in a custom thread at startup and just .get() it at the end, would save a few time probably.

**Comment by rmpestano** [comment]
I am looking foward a way to unit test the Observer with arquillian guys but if we don't find any clean way we go with current approach.

About the side note tou mean something like this: https://github.com/rmpestano/arquillian-asciidoctor-extension/blob/0ddbe02a2a95a1239ee265ce2a6df47b4ec487df/src/main/java/com/github/cukespace/arquillian/asciidoctor/AsciidoctorObserver.java#L156

or you mean call "render" method asynchronous?

**Comment by rmannibucau** [comment]
no you got it right, idea is to observer ManagerStarted too and create in an asynchronous manner adoc instance then in ManagerStopped we just .get() the value which should be already there

**Comment by rmpestano** [comment]
apparently working: https://github.com/rmpestano/arquillian-asciidoctor-extension/blob/07c20af5ba4b4110bb1cadc35b02694a00c0556f/src/main/java/com/github/cukespace/arquillian/asciidoctor/AsciidoctorObserver.java#L63

**Comment by rmannibucau** [comment]
new Thread is fine too and ensure we dont leak a thread if not daemon. Should also be named pby but that is exactly the idea. Did you estimate the time gained? Maybe preloading libs helps too (for pdf?)

**Comment by rmpestano** [comment]
closing as I see no issues in linux with pdf backend.

**Comment by rmpestano** [comment]
Hi Romain,

I see no real improvement in time (measured by using system.currentTime in ManagerStarted and stop events)
